"""Sync existing tables

Revision ID: 9b2f0eb61d74
Revises: 
Create Date: 2025-04-18 00:55:44.626437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2f0eb61d74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voters_id', table_name='voters')
    op.drop_index('ix_voters_name', table_name='voters')
    op.drop_table('voters')
    op.drop_index('ix_elections_id', table_name='elections')
    op.drop_index('ix_elections_name', table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('candidates', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('votes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='elections_pkey')
    )
    op.create_index('ix_elections_name', 'elections', ['name'], unique=False)
    op.create_index('ix_elections_id', 'elections', ['id'], unique=False)
    op.create_table('voters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_voted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='voters_pkey')
    )
    op.create_index('ix_voters_name', 'voters', ['name'], unique=False)
    op.create_index('ix_voters_id', 'voters', ['id'], unique=False)
    # ### end Alembic commands ###
